wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.5
    start_time: 1686742913.661244
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.10.5
      5: 0.13.5
      8:
      - 1
      - 3
      - 5
